spring:
  application:
    name: Url Shortener

  datasource:
    url: jdbc:mysql://localhost:3306/url
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  base-url: http://localhost:8080